### ISSUE TITLE
Questions about this extension

### ISSUE THREAD

**Issue by BigFlubba** [jeroentvb/spicetify-combined-playlists#1]
Is this extension local only? I know of a site that allows you to do this, but that site does not work. Can this extension do this outside of being locally? It is a shame that this is not native to vanilla clients for everyone.

**Comment by jeroentvb** [comment]
> It is a shame that this is not native to vanilla clients for everyone.

I agree, that's why I made this.

It's local only in the sense that it runs locally, but it does use the spotify API.  
Any request to the spotify API is authenticated with account of the user when making the request within spicetify/spotify. This has 2 benefits: 
* I don't need to request a spotify API key, since the users account is being used
* No need to grant the app permission to read private playlists, since the app can access that via the authenticated API calls (and technically you're already granting permission by installing the app).
    - This is somewhat of a privacy risk, as by using the API, an app can access playlist data/user info e.t.c. But this is the case for every extension/custom app and any website you allow access to your account. Make sure you trust the extension/app/website before using it. But I hope that speaks for itself.

The code that gathers playlist data and combines them into one playlist can be re-used by an online service, but then I'd need to request an API key, and need to ask users for permission to use their playlist data.

**Comment by BigFlubba** [comment]
>I know of a site that allows you to do this, but that site does not work.
>>You're talking about http://smarterplaylists.playlistmachinery.com/ right? That was indeed an alternative to this.

No, I was referencing this site https://www.playlistmerger.com/.
I also found out that, that site doesn't work.

**Comment by jeroentvb** [comment]
If you don't want to, or can't use spicetify, you could send them an issue report via the website here: https://www.playlistmerger.com/contact.html

**Comment by jeroentvb** [comment]
Have your questions been answered? If so you or I can close this issue.
