### ISSUE TITLE
How do I unInstall this?

### ISSUE THREAD

**Issue by Jeep012** [jeroentvb/spicetify-combined-playlists#14]
It is currently just making me restart spotify everytime i try to use this app

**Comment by jeroentvb** [comment]
I would like to know why it is crashing for you, because I've had a few others with I'm guessing the same issue, but the app always seems to be working for me.

If you're willing to check the following, that would help me a lot.
* Check if `spicetify apply` is showing any errors in regard to combined-playlists
* Open the console (first enable devtools `spicetify-enable-devtools`), navigate to combined-playlists and see what error is being thrown (a sceenshot from the console is very helpful)

If you're not willing to help, here are some uninstall instructions:
1. In an terminal enter spicetify config-dir
2. Remove the combined-playlists folder
3. Open config-xpui.ini
4. Remove combined-playlists from the custom_apps entry, and save the file
5. Enter spicetify apply in a terminal window

**Comment by M1l0rd** [comment]
"error Custom app "combined-playlists" does not have index.js"

**Comment by M1l0rd** [comment]
yes, and the app page doesn't work, it keeps asking to reload the page

**Comment by jeroentvb** [comment]
Make sure the `combined-playlists` folder in the `CustomApps` folder contains the app files, including `index.js`, *not* another folder with those files nested inside. Then re-do `spicetify apply`

**Comment by jeroentvb** [comment]
Can either of you confirm if this solves the issue? Because then I'll need to update the readme @Jeep012 @M1l0rd

**Comment by davideAurum** [comment]
I had the exact same issue described, and this was the fix.
