### ISSUE TITLE
2 issues in 1 post

### ISSUE THREAD

**Issue by BCano05** [jeroentvb/spicetify-combined-playlists#9]
Hi so i have 2 problems when trying to install 
1. In my User profile folders (im using windows) theres never a spicetify folder 
2. When trying to install the combined playlist i copied  this code: iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex 
in my powe shell and when i did that the program kind of install but when i hit the combined playlist button its said theres been a problem( like in the photo)
I really want to use the program so it would be a big help if someone could help
![image](https://user-images.githubusercontent.com/124320180/216486624-efb68403-e102-464a-b6bf-191dd2c67538.png)
![image](https://user-images.githubusercontent.com/124320180/216486750-c9b741ca-4ce1-4273-8b46-2cdd6900cedc.png)

**Comment by jeroentvb** [comment]
I don't understand how you've installed combined playlists, since you've only linked the install scripts for spicetify cli and spicetify marketplace. Where did you copy the combined-playlists folder to, and did you get it from the dist branch of this repo?

Anyway, the steps to install:

1. Download the `combined-playlists` folder from the [dist](https://github.com/jeroentvb/spicetify-combined-playlists/tree/dist) branch
2. Enter `spicetify config-dir` in powershell
3. Copy the `combined-playlists` folder to the CustomApps folder in the explorer window that opened in step 2
4. Enter the following 2 commands in powerhsell `spicetify config custom_apps combined-playlists` and `spicetify apply`

**Comment by BCano05** [comment]
I have  fix it now thx
